<a href="https://colab.research.google.com/github/dhrubasaha001/AI_ML_Data-Science_Roadmap/blob/main/Basics_Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
my_list=[1,2,3]

In [ ]:
array=np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
print(array)

[1 2 3]


In [ ]:
print(my_list*2)

[1, 2, 3, 1, 2, 3]


In [ ]:
print(array*2)

[2 4 6]


In [ ]:
print(array[0])

1


In [ ]:
print(array[0:7])

[1 2 3 4 5 6 7]


In [ ]:
print(type(array))

<class 'numpy.ndarray'>


In [ ]:
print(array.dtype)

int64


In [ ]:
print(array.shape)

(10,)


In [ ]:
two_d_array=np.array([[1,2,3],[4,5,6]])

In [ ]:
print(two_d_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(type(two_d_array),two_d_array.dtype,two_d_array.shape)

<class 'numpy.ndarray'> int64 (2, 3)


In [ ]:
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [ ]:
n2=np.zeros((3,4))
n2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
n3=np.zeros((2,2,2))

In [ ]:
n3

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
n4=np.full((2,2),69)
n4

array([[69, 69],
       [69, 69]])

In [ ]:
n1=np.arange(1,10,2)
n1

array([1, 3, 5, 7, 9])

In [ ]:
# Random Integer array randint(this ,to this random number , required random number)
n1=np.random.randint(1,10,5)
n1

array([1, 1, 1, 9, 3])

In [ ]:
n6=np.array([[10,20,30],[40,50,60]])
n6

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
n6.shape

(2, 3)

In [ ]:
n6.shape=(3,2)
n6

array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
n7=np.array([10,20,30])
n8=np.array([40,50,60])
np.vstack((n7,n8))

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
np.hstack((n7,n8))

array([10, 20, 30, 40, 50, 60])

In [ ]:
np.column_stack((n7,n8))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([20,30,40])
# np.intersect1d(n1,n2)
# np.setdiff1d(n1,n2)
# np.setdiff1d(n2,n1)
# np.sum((n1,n2))
# np.sum((n1,n2),axis=0)
# np.sum((n1,n2),axis=1)
np.mean(n1)
np.std(n1)
np.median(n1)

np.float64(20.0)

In [ ]:
n1=np.array([[10,20,30],[40,50,60],[70,80,90]])
n2=np.array([[90,80,70],[60,50,40],[30,20,10]])
# n1[0,:]
# n1[:,0]
# n1.transpose()
# n2.dot(n1)
# n1.dot(n1)
np.save('my_numpy.npy',n1)
n3=np.load('my_numpy.npy')
n3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])